<?php if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly
$codes = array(
    array( 'code' => 'category_name',  'description' => __( 'name of category', 'bookly' ), ),
    array( 'code' => 'login_form',     'description' => __( 'login form', 'bookly' ),
        'step'        => 6,
        'login'       => true,
    ),
    array( 'code' => 'number_of_persons', 'description' => __( 'number of persons', 'bookly' ), ),
    array( 'code' => 'booking_number', 'description' => __( 'booking number', 'bookly' ),
        'step'        => 8,
    ),
    array( 'code' => 'service_date',   'description' => __( 'date of service', 'bookly' ),
        'min_step'    => 3,
    ),
    array( 'code' => 'service_info',   'description' => __( 'info of service', 'bookly' ), ),
    array( 'code' => 'service_name',   'description' => __( 'name of service', 'bookly' ), ),
    array( 'code' => 'service_price',  'description' => __( 'price of service', 'bookly' ), ),
    array( 'code' => 'service_time',   'description' => __( 'time of service', 'bookly' ),
        'min_step'    => 3,
    ),
    array( 'code' => 'staff_info',     'description' => __( 'info of staff', 'bookly' ), ),
    array( 'code' => 'staff_name',     'description' => __( 'name of staff', 'bookly' ), ),
    array( 'code' => 'total_price',    'description' => __( 'total price of booking', 'bookly' ), ),
);
\BooklyLite\Lib\Utils\Common::Codes( apply_filters( 'bookly_prepare_appearance_short_codes', $codes ), $step, isset( $login ) ? $login : false );